# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-04 04:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20170504_0002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeuser',
            name='password',
            field=models.CharField(max_length=2000),
        ),
    ]
